DEBUG : False
seed : 42
epochs : 45
train : True
folds : [0]
img_size : 224
main_metric : "f1_at_05"
minimize_metric : False
train_datadir : "../../../input/birdclef-2022/train_audio"
test_datadir : ../../input/birdclef-2022/train_audio/akepa1
train_csv : "../../../input/birdclef-2022/train_metadata.csv"
model_path : model.best.pth

project_name : "birdclef2022"
second_label : True

transforms : {
    "train": [{"name": "Normalize"}],
    "valid": [{"name": "Normalize"}],
    "test": [{"name": "Normalize"}]
}
threshold : 0.1
period : 20
n_mels : 128
fmin : 20
fmax : 16000
n_fft : 2048
hop_length : 512
sample_rate : 32000
melspectrogram_parameters : {
    "n_mels": 224,
    "fmin": 20,
    "fmax": 16000
}

target_columns : [
    "afrsil1","akekee","akepa1","akiapo","akikik","amewig","aniani","apapan",
    "arcter","barpet","bcnher","belkin1","bkbplo","bknsti","bkwpet","blkfra",
    "blknod","bongul","brant","brnboo","brnnod","brnowl","brtcur","bubsan",
    "buffle","bulpet","burpar","buwtea","cacgoo1","calqua","cangoo","canvas",
    "caster1","categr","chbsan","chemun","chukar","cintea","comgal1","commyn",
    "compea","comsan","comwax","coopet","crehon","dunlin","elepai","ercfra",
    "eurwig","fragul","gadwal","gamqua","glwgul","gnwtea","golphe","grbher3",
    "grefri","gresca","gryfra","gwfgoo","hawama","hawcoo","hawcre","hawgoo",
    "hawhaw","hawpet1","hoomer","houfin","houspa","hudgod","iiwi","incter1",
    "jabwar","japqua","kalphe","kauama","laugul","layalb","lcspet","leasan",
    "leater1","lessca","lesyel","lobdow","lotjae","madpet","magpet1","mallar3",
    "masboo","mauala","maupar","merlin","mitpar","moudov","norcar","norhar2",
    "normoc","norpin","norsho","nutman","oahama","omao","osprey","pagplo",
    "palila","parjae","pecsan","peflov","perfal","pibgre","pomjae","puaioh",
    "reccar","redava","redjun","redpha1","refboo","rempar","rettro","ribgul",
    "rinduc","rinphe","rocpig","rorpar","rudtur","ruff","saffin","sander",
    "semplo","sheowl","shtsan","skylar","snogoo","sooshe","sooter1","sopsku1",
    "sora","spodov","sposan","towsol","wantat1","warwhe1","wesmea","wessan",
    "wetshe","whfibi","whiter","whttro","wiltur","yebcar","yefcan","zebdov",
]

all_birds : {
afrsil1 : 0, akekee : 1, akepa1 : 2, akiapo : 3, akikik : 4, amewig : 5, aniani : 6, apapan : 7, 
arcter : 8, barpet : 9, bcnher : 10, belkin1 : 11, bkbplo : 12, bknsti : 13, bkwpet : 14, blkfra : 15, blknod : 16,
bongul : 17, brant : 18, brnboo : 19, brnnod : 20, brnowl : 21, brtcur : 22, bubsan : 23, buffle : 24,
bulpet : 25, burpar : 26, buwtea : 27, cacgoo1 : 28, calqua : 29, cangoo : 30, canvas : 31, caster1 : 32,
categr : 33, chbsan : 34, chemun : 35, chukar : 36, cintea : 37, comgal1 : 38, commyn : 39, compea : 40,
comsan : 41, comwax : 42, coopet : 43, crehon : 44, dunlin : 45, elepai : 46, ercfra : 47, eurwig : 48,
fragul : 49, gadwal : 50, gamqua : 51, glwgul : 52, gnwtea : 53, golphe : 54, grbher3 : 55, grefri : 56,
gresca : 57, gryfra : 58, gwfgoo : 59, hawama : 60, hawcoo : 61, hawcre : 62, hawgoo : 63, hawhaw : 64,
hawpet1 : 65, hoomer : 66, houfin : 67, houspa : 68, hudgod : 69, iiwi : 70, incter1 : 71, jabwar : 72,
japqua : 73, kalphe : 74, kauama : 75, laugul : 76, layalb : 77, lcspet : 78, leasan : 79, leater1 : 80,
lessca : 81, lesyel : 82, lobdow : 83, lotjae : 84, madpet : 85, magpet1 : 86, mallar3 : 87, masboo : 88,
mauala : 89, maupar : 90, merlin : 91, mitpar : 92, moudov : 93, norcar : 94, norhar2 : 95, normoc : 96,
norpin : 97, norsho : 98, nutman : 99, oahama : 100, omao : 101, osprey : 102, pagplo : 103, palila : 104,
parjae : 105, pecsan : 106, peflov : 107, perfal : 108, pibgre : 109, pomjae : 110, puaioh : 111, reccar : 112,
redava : 113, redjun : 114, redpha1 : 115, refboo : 116, rempar : 117, rettro : 118, ribgul : 119, rinduc : 120,
rinphe : 121, rocpig : 122, rorpar : 123, rudtur : 124, ruff : 125, saffin : 126, sander : 127, semplo : 128,
sheowl : 129, shtsan : 130, skylar : 131, snogoo : 132, sooshe : 133, sooter1 : 134, sopsku1 : 135, sora : 136,
spodov : 137, sposan : 138, towsol : 139, wantat1 : 140, warwhe1 : 141, wesmea : 142, wessan : 143, wetshe : 144,
whfibi : 145, whiter : 146, whttro : 147, wiltur : 148, yebcar : 149, yefcan : 150, zebdov : 151 }


loader_params : {
    "train": {
        "batch_size": 64,
        "num_workers": 4,
        "shuffle": True
    },
    "valid": {
        "batch_size": 64,
        "num_workers": 4,
        "shuffle": False
    }
}

split : "StratifiedKFold"
split_params : {
    "n_splits": 5,
    "shuffle": True,
    "random_state": 1213
}

base_model_name : "tf_efficientnet_b0_ns"
pooling : "max"
pretrained : True
num_classes : 152
in_channels : 1

loss_name : "BCEFocal2WayLoss"

loss_params: {}

optimizer_name : "Adam"
base_optimizer : "Adam"
optimizer_params : {
    "lr": 0.0008
}

base_optimizer : "Adam"
scheduler_name : "CosineAnnealingLR"
scheduler_params : {
    "T_max": 10
}
