wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1647748455
    t:
      1:
      - 1
      - 5
      - 18
      - 41
      3:
      - 13
      4: 3.8.10
      5: 0.12.11
      8:
      - 1
      - 2
      - 5
